apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: template
data:
  HOST: "0.0.0.0"
  PORT: "8080"
  POSTGRES_HOST: "postgres-postgresql.template.svc.cluster.local"
  POSTGRES_PORT: "5432"
  DEBUG: "false"
