apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: template
type: Opaque
stringData:
    TOKEN_SECRET: ENC[AES256_GCM,data:aSYb+oekL9gx477QQHGipr1O8Dn9QLSb5T4Ql/AXWZecAyu2YPG3NxKGubg=,iv:V3HnHwUHlSwlP19niC6PB/bnOYo6gts6wh2eUNqz5R8=,tag:sT3gET2caVRJwZxc7PweEw==,type:str]
    GOOGLE_ACCESS_KEY_ID: ENC[AES256_GCM,data:H6OdOCsxLqn09qlGF2x4HMu1NyqDxD3KKHQDPsAevJ3uHqtQt14DY0BptHVBUfVKlOx9T3ckhZeWlxXgGb4mwalQRWSPIU/O,iv:Ya+c2aTviXXMK0CH84C3QVQei6CZi9bPrmnmmMeHvXs=,tag:4eA176guHxZbYjZtX8OYpA==,type:str]
    GOOGLE_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:1qVh3ymAC8aF6KQE696luwoyxBL8jkWYA0RojtFCSbkOTu0=,iv:e5wpw8cxXzKzl4Z53tr3vSlhdeGpHI/pIE0eXm+SSRQ=,tag:166iUxOCLrV4D50igRv2jQ==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUGhmWjk3aUt3ZXEvcjUx
            ZUlYOTlrdkV5UEFVbFk2R3ZCc3RxY1Q4TG1NCi9tMFZrNHVMZmNsSTEvVmNhUml6
            YlB0WlBCUk9oeFMrMXI1ZGYwOWREV2cKLS0tIG50NVZieGFjbGh1R09wL3RiNGhq
            Tm42aHlidy9pSHNEbWRQdU9SRHVmZlkK8peDk4tarFfeowUZpZucfOUA0q/+F6jk
            iAuEEbqfU2G11lKfq0vhF0AehPOo+dGbeUankTKIlGY46uBFfBXPsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T08:54:54Z"
    mac: ENC[AES256_GCM,data:jLW351tKa3g6yDwVUdbrBjs0KpwmdudxE/eIzub39fAWuRlDf+j7jfjWa/Hj1IkGhMfI9K9d34YJ3pfevclEnsBAY8ovTRjw0VS0LNEiE5WQaNPp5Nsg1y8GZ3ezHSIxp3RIyWZ7v+36tBjF7yBDK6ymIsFe57I97h85HTRdc/o=,iv:dSOW7NHuBe+dQT1+bQQXrPd+5rk2peFKanZChl0eMtA=,tag:UgV37rIkxQ1IuXDDHAdKmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
