apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: template
type: Opaque
stringData:
    token-secret: ENC[AES256_GCM,data:B743VsQ3nWlJEA4XwU4Jzf9JYmPKaPGNrUxC/eyeIDgjx7yj06gVUwHfSaU=,iv:kwOZsBcAfNdktF9LuLBkyHKO5EgullRTF7jvYCxG+7s=,tag:t4N+Mgg7utObIVIaA80Leg==,type:str]
    google-access-key-id: ENC[AES256_GCM,data:YndxXggoskEQXH+YXcYH0K7wU1dHDD8t/qA/MgrggvZkE4sRyTvXm6OPXIBkOoDaZzJt52fB2Zho4JEnsJDPNsrX8aAA+kvE,iv:w5qPHgQzq3pSh7k2fCKzi3Cc6YPwvtGDEaQSGxZOPh8=,tag:S41ayCYMFfe2w48LtQYogw==,type:str]
    google-secret-access-key: ENC[AES256_GCM,data:cc2XkcXO2qUkOwVVj0hegijzyfuoH2btF9nndGZnmGHpoIE=,iv:Hm+f2wG4gaavOLuI6FtUW4rUeTlRF4bhWH7pOUmgra4=,tag:JYGBQOG4QJiKwrRbI3hAog==,type:str]
    database-url: ENC[AES256_GCM,data:ggMye3+RRwwUZErfGlS1NqunpeSOEJgwzcf3GEp9lnksNpXPf8YPjxM+ecA3aq23pmD/ycwHfRvRljxbhbboqY2IGvOVtUyNmPjSfUJ50gfYB/l8kWiwQbCQgU9jXUm/aARj88pzbi+VnbMj,iv:b+uYeoExtWkdiwIGtccCraVSC4ODaP+A/LvaHzBmMLM=,tag:hG2pjvlt+g/9LIvMsbvbhg==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1BhcHh4RmtRTGxwUENI
            TS9TSkMvZUx1QXdXMENpSExOVlF1VUxqVFVnCklFWllFbEtjeXVZNStvUmpYK29n
            UTBGSkp2bi9VQk1KVzhCZnNSem1SV0kKLS0tIDZZMW9vcHlodHd6cld4S1ZBS1o2
            alVHOHJBem41TDlZdzZtMlh3SitwZGcKGf5HnbWVCkKLN5wM0utulR/Iq696ItMP
            iv9oEYwpo8NdrH2Y4tzd+YPAbOVZY0GFKxj8fz5uxW1Q7fZd740gHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T10:51:20Z"
    mac: ENC[AES256_GCM,data:4LvwddzNTqbBuTOTwHAWnorD2+zGBeZPwr5mCdB/8UMjY/iAyg8SRY3EEDvA0x2qZkHL77IphmAFaSTFXBCwAsvFsFyL/jR0IvtA0MUs7gK/O+cYKZg6L9V6kt/RMCXAgVrFPWhClk7ntoYzsFJ+9+CmTrVP+0jaC9anvEHZfek=,iv:jqkllRpxlvwfUj2Z8aDsBi3eX2Oe87ZKXGL+JR5oILY=,tag:pmtzzVQwG4sAxK6a/5ByeA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
