apiVersion: v1
kind: Secret
metadata:
    name: api-secrets
    namespace: template
type: Opaque
stringData:
    token-secret: ENC[AES256_GCM,data:B743VsQ3nWlJEA4XwU4Jzf9JYmPKaPGNrUxC/eyeIDgjx7yj06gVUwHfSaU=,iv:kwOZsBcAfNdktF9LuLBkyHKO5EgullRTF7jvYCxG+7s=,tag:t4N+Mgg7utObIVIaA80Leg==,type:str]
    google-access-key-id: ENC[AES256_GCM,data:YndxXggoskEQXH+YXcYH0K7wU1dHDD8t/qA/MgrggvZkE4sRyTvXm6OPXIBkOoDaZzJt52fB2Zho4JEnsJDPNsrX8aAA+kvE,iv:w5qPHgQzq3pSh7k2fCKzi3Cc6YPwvtGDEaQSGxZOPh8=,tag:S41ayCYMFfe2w48LtQYogw==,type:str]
    google-secret-access-key: ENC[AES256_GCM,data:cc2XkcXO2qUkOwVVj0hegijzyfuoH2btF9nndGZnmGHpoIE=,iv:Hm+f2wG4gaavOLuI6FtUW4rUeTlRF4bhWH7pOUmgra4=,tag:JYGBQOG4QJiKwrRbI3hAog==,type:str]
    database-url: ENC[AES256_GCM,data:AL6hqgrKd8H+537I/RkL9FMBqNQAQZqqFBS5cl0hvZsCV31OPCg87msIQtEKAQqFvMtoN0ehW3scOIiO97x2RXHDwkeAb62DJ80/Ye8nqAoLbJwD1LnFfrBbwInkYwh351T9fZLrqshl5VEJ,iv:JpDGiPwvsEO/Lu5A2/A15q2sBY6xEQk60L88EVXNBBE=,tag:K9VN5j+MQMySugqOi3f2XA==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnY1BhcHh4RmtRTGxwUENI
            TS9TSkMvZUx1QXdXMENpSExOVlF1VUxqVFVnCklFWllFbEtjeXVZNStvUmpYK29n
            UTBGSkp2bi9VQk1KVzhCZnNSem1SV0kKLS0tIDZZMW9vcHlodHd6cld4S1ZBS1o2
            alVHOHJBem41TDlZdzZtMlh3SitwZGcKGf5HnbWVCkKLN5wM0utulR/Iq696ItMP
            iv9oEYwpo8NdrH2Y4tzd+YPAbOVZY0GFKxj8fz5uxW1Q7fZd740gHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T11:19:39Z"
    mac: ENC[AES256_GCM,data:AIYT3eszVqj4jN71/ipDH3QNGNic2mVWa6ocXAPZb4I2GYEWRUf9ab46a4nA2zXQct100S6ebxSlygeLGNFbzM7QOVa/Le8yXpUDFE04ZvdQKCxJtgEQCUL9oqSQCZH4+/maqmRWNo1NJV/tOd+FAxRStoGe4knq61Whkrxzwus=,iv:IBFLksZ8+bPeDyHglMvgC049Vm01auDd7Y9azwz+2lg=,tag:hWzG2x02v4mjeDHFXtkExg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
