apiVersion: v1
kind: Secret
metadata:
    name: postgres-secrets
    namespace: template
stringData:
    admin-pass: ENC[AES256_GCM,data:dLEh5Q5WRp66qTQvi87axg==,iv:LU5TdaSDasVC9FPows3sAR0lJv3wUfHvOBegfzUYCVU=,tag:FP904fVjk0f02Yr9YQvPfg==,type:str]
    user-pass: ENC[AES256_GCM,data:bqpkctSHC0j8s3QOQfgB,iv:rA6lMh/QPHUXrH1GeBW6QCJhzs8L1Aywxpbr+p4aGqU=,tag:V0kFdyOz5q4oq0rZv8XFBA==,type:str]
sops:
    age:
        - recipient: age1g752ky89kud2ldcgfvyzvdgsx98ydr3cwjzpk460m7mztr3ne48ssme2l9
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3MDFtZlgvNjl0enVINUVn
            U1FHczVMRW9jcGhmdlVpOUJVNWlvcVorelMwCmQydTNQbUZXVHZLREFONnFVNS9u
            MDRwRUdTTG5xUkhmckg2clA3ZGh2MGMKLS0tIHFuVWZBT3R1MHNsSzhqQ0JnSTBs
            eURoQlpzcXh1M01lekFqdEJEOUNVQlkKzGJ3FrD5uENsMp+rtl2lYqodD5mLM6rJ
            j67Y1krDXaKGiHCeWTVc8Y1rEM4ZcP9vTzGq3xy20jrP1cw2VnIrFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T09:55:38Z"
    mac: ENC[AES256_GCM,data:cdJwRhT610hjVeh+DZVkzmFJBy+D7fGIE4YCQAhyzRk+MO/LPueMygnUrcZv0qAZ7i4VBgOs61r5xymZIPuLrFwYOKcCNQ6a3QvCQgJ6He/ex9ej3pIpqKZxT8cZ5zEWEL4mTKZaefjmYHBYR4d5JnYY5+WMbdIrkpJXgobJDcA=,iv:g5JtGXBz3oF096wbxtMrzOYLLPiCpR3DjjDbyvGRLxQ=,tag:Gp/EfzJFhBCMM/GE5sKzPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
